### PR TITLE
Replaced self-closing anchor tags with full anchor tags

### PR DESCRIPTION
**Pull request by rswetnam**
Hi:

Don't know if this is much of a problem else where but my code editor (Visual Studio Code) does not handle self-closing anchor tags well and in previews and leaves great swaths of text following an opening tag as apparent hyperlinks.  I did a search for "/> and replaced with "></a>" and it fixed things.   I think such a change would make the xAPI document more acceptable a wider range of Markdown readers without affecting readability in any Markdown readers that are currently able to interpret these links.

### CODE REVIEW

**Comment by garemoko** [comment]
I'm +1 to this, however can we wait until after #775 merges as I suspect there may be a conflict and this PR is probably easier to re-do or de-conflict.

**Comment by andyjohnson** [comment]
Your suspicions are confirmed.  Shouldn't be too hard to fix.

**Comment by garemoko** [comment]
Probably the least risky and fastest thing is for somebody to re-do this commit and PR off the current version.

**Comment by andyjohnson** [comment]
I think we can probably leave this alone until it is time for full document edits.  It can either be done quickly before the edits or rolled into other full-document sweeps.

**Pull request closed without merging**
