### PR TITLE
Update readme for 1.0.3 release

### PR DESCRIPTION
**Pull request by garemoko**

### CODE REVIEW

**Comment by andyjohnson** [comment]
+1

**Comment by garemoko** [comment]
@oconnetf that's fixed now. Thanks for spotting that.

**Comment by oconnetf** [comment]
Seems like you might also want to update this bit? "...fixed in the development version of the specification (1.0.3)..." Including the link, I imagine. Otherwise, it's a bit inconsistent with the assertion of "current version".

**Comment by garemoko** [comment]
@oconnetf Good point. We'll have to think about the best approach for that section. Possibly we'll just have to delete that paragraph as I'm not sure there will be a development version for a little while once 1.0.3 releases. Maybe that's wishful thinking :-)

@andyjohnson

**Comment by garemoko** [comment]
I've proposed a change. We can always add that wording back in once a development version exists again.

**Comment by andyjohnson** [comment]
I like it!  (Especially not planning another release) +1

**Comment by oconnetf** [comment]
+1

**Pull request merged**
