### PR TITLE
Content negotiation errors

### PR DESCRIPTION
**Pull request by fugu13**

### CODE REVIEW

**Comment by fugu13** [comment]
This is an addition discussed in #538, though not itself part of the 538 fix.

**Comment by garemoko** [comment]
Looks good, but can we add a link to either http://en.wikipedia.org/wiki/Content_negotiation or http://tools.ietf.org/html/rfc7231#section-5.3 ? I prefer the RFC.

**Comment by fugu13** [comment]
Add content negotiation RFC link

**Comment by garemoko** [comment]
Looks good. +1.

**Pull request merged**
