### PR TITLE
Four issues in section 7

### LINKED ISSUE #601: LRS can support additional resources
Consider adding something to https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#71-error-codes to say that the LRS can support additional resources not in the spec and add error code 405 to the list of example codes. 

See https://github.com/adlnet/xAPI_LRS_Test/issues/24

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #601 #671 #674 #656

### CODE REVIEW

**Comment by andyjohnson** [comment]
I wonder about the SHOULD* aspect of some of these.  The Last-Modified requirement seems like it would be the only acceptable behavior for an LRS, but I haven't implemented one - is this the case?

I have more of an issue with the defined additional endpoints all going under /extensions.  I agree it is at least a SHOULD and I agree that in 2.0, we could move all non-xAPI endpoints there (with a MUST), but where this breaks down, in my opinion, is in the intent of the SHOULD*.  SHOULD*s have been essentially restricted to the only possible or only reasonable practice, but without supporting spec language to justify a MUST.  I feel this is a bit different.  It is perfectly reasonable that other endpoints were defined for an LRS and not mapped to /extensions in 1.0.2.  If implementors were thinking of future interoperability, they may have decided placement in extensions is appropriate, but that may be applying our goals to someone just building a product.

**Comment by garemoko** [comment]
I agree that we do seem to have a disconnect in our understanding of 'SHOULD'. My understanding was that SHOULD is simply a recommendation of best practice and that we were ok with adding additional best practices in 1.0.3 that were not in 1.0.2.

**Comment by andyjohnson** [comment]
I shouldn't beat around the bush so much, or if I do, at least say what I think at the end:

SHOULD* for "Last-Modified" :+1:  SHOULD (regular) for the endpoint :+1: 

I have no doubt we would, in a 2.0 version, force additional endpoints into this bucket, but don't feel it should have the weight in 1.0.3 of a SHOULD*.

**Comment by garemoko** [comment]
That first star is now removed.

**Comment by andyjohnson** [comment]
+1 for you @garemoko !  And a free :hamburger:

**Pull request merged**
