### PR TITLE
Clarifications on Immutability

### PR DESCRIPTION
**Pull request by garemoko**
Addresses https://github.com/adlnet/xAPI-Spec/issues/484

### CODE REVIEW

**Comment by garemoko** [comment]
From call: make clear that attachments are not part of statements so when statements are returned by an LRS without attachments (GET statements with attachments: false) that doesn't affect immutability.

**Comment by andyjohnson** [comment]
I think we still need a bit more text around saying "Display is not part of a verb".  Perhaps an update to the format entry in the 7.2.3 table to include Verbs?  I think it would also be useful to mention that any property containing a language map is essentially mutable as it is a collection of languages, of which, any subset can be used.

**Comment by andyjohnson** [comment]
Aha!  I thought I remembered a PR with it in there and thought I had merged it already.  You are right about the extensions, and at that point any value we gain by referring to "all language maps" becomes lost.  Agree with calling each of them out specifically.

**Comment by andyjohnson** [comment]
So yeah, +1

**Pull request merged**
