### PR TITLE
Content types

### PR DESCRIPTION
**Pull request by garemoko**
Addresses #868, #859, #871 and #881

### CODE REVIEW

**Comment by garemoko** [comment]
It may help to review individual commits. 869ed68 is cut and paste only with zero edits.

**Comment by andyjohnson** [comment]
Thanks for doing a lot of the cross document linking in this too!  Can you grab Formatting Requirements in Part 3, it seems to be broken at the moment?  Otherwise +1 on this relocation and TOC updates.

**Comment by garemoko** [comment]
@andyjohnson sorry i don't follow, what's broken?

**Comment by andyjohnson** [comment]
Sorry I hadn't see this.  In xAPI-Communication.md's Table of Contents, "Formatting Requirements" Part 2 - Section 2.2, is the only one that doesn't have the full path for the anchor.

**Comment by garemoko** [comment]
@andyjohnson done!

**Comment by ljwolford** [comment]
+1

**Pull request merged**
