### PR TITLE
Update xAPI.md

### PR DESCRIPTION
**Pull request by jhaag75**
Updates to use of the term "profile" based on this issue: https://github.com/adlnet/xAPI-Spec/issues/496

### CODE REVIEW

**Comment by fugu13** [comment]
It looks like you accidentally changed the copyright year from 2013 to 201. I haven't looked at it beyond that, but could you back this out and then reopen as a PR?

**Comment by jhaag75** [comment]
Sure. Just merged it back to the other. Not sure what happened there. Sorry
about that!

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by garemoko** [comment]
Looks like this commit is still in the 1.0.3 branch.

**Comment by garemoko** [comment]
Sometimes maybe it feels like we've been doing this since 201 :-p

**Comment by andyjohnson** [comment]
Jason just went dark (navy base) for a couple days and likely won't have access.  We're also tightening up rogue merges :p

**Pull request merged**
