### PR TITLE
Replace "cannot use attachments" with "does not send the contents of attachments"

### LINKED ISSUE #858: Replace "cannot use attachments" with "does not send the contents of attachments"
The [Requirements for Attachment Statement Batches](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#requirements-for-attachment-statement-batches) allow for LRSs responding to a GET request where the attachments flag is true to respond in two different ways. In the response includes attachments then the response is multi-part/mixed, if fileUrls are used then the response is application/json. 

(Side note: I take this to mean not that the LRS is allowed to choose to include either actual attachments or fileurls, but that the LRSs response is determined by the statements that happen to be  in the batch, because immutability. This could be clearer). 

We don't say how the LRS can/should respond if there are no attachments at all. Presumably either approach is OK. Should we make a recommendation one way or another for consistency? I think I'd lean towards using application/json.

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #858

### CODE REVIEW

**Comment by garemoko** [comment]
Should this be "attachment data" instead of "content of attachments"?

**Comment by fugu13** [comment]
Looking it over, it looks like we use that already for the bodies of the attachments themselves, so "attachment data" should be fine.

**Comment by garemoko** [comment]
@fugu13 yeh, I got the term from the Attachments section.

**Comment by andyjohnson** [comment]
+1

**Comment by ljwolford** [comment]
+1

**Pull request merged**
