### PR TITLE
Rewrote based on 1.0.3-Restructure

### PR DESCRIPTION
**Pull request by canweriotnow**
Resubmission of #802 based on feedback from @garemoko

### CODE REVIEW

**Comment by garemoko** [comment]
@canweriotnow thanks for making this. I think whatever editor your using is making a bunch of whitespace changes which make the PR very difficult to review and in some cases mess up the formatting of the document by putting stuff on one line that's supposed to be split over multiple lines. 

If there's any way you can recreate this without the whitespace changes, that'd be great. Possibly somebody with better Git knowledge than I can suggest a way to ignore all the whitespace changes. 

Just to make things simpler, I'll also incorporate your change to CONTRIBUTING.md into #793 to avoid conflicts and the need for you to work with two files.

**Comment by canweriotnow** [comment]
@garemoko I think Emacs' markdown-mode is opinionated about whitespace, and the spec as she is wrote doesn't follow "typical" practices for Github-flavoured markdown... seems to be a lot too much space and a lot of embedded HTML where Markdown provides facilties for what's going on... Since you incorporated the CONTRIBUTING change into #793 I'll try editing one more time, maybe just w/ the Github web editor, and see if that doesn't solve the problem. 

But if it does, I'll probably open a whitespace-cleanup issue so Vim and Emacs users aren't frustrated by the whitespace situation :smile_cat:

**Comment by canweriotnow** [comment]
Going to close and resubmit for sanity;s sake.

**Comment by garemoko** [comment]
I'm not against a whitespace pr so long as it's done when there's no other open prs to avoid conflict and the rendered markdown is checked carefully. 

I suggest it's done as the first commit after 1.0.3 lands to avoid affecting version diffs. I also suggest doing it from a specially created github account to avoid distorting the contribution graphs.

**Pull request closed without merging**
