### PR TITLE
Example SubStatement object missing objectType

### PR DESCRIPTION
**Pull request by ty-**
Added "objectType": "Activity"

### CODE REVIEW

**Comment by brianjmiller** [comment]
Should be a fine change, but presumably the assumption of "Activity" in an 'object' property applies to SubStatements as well as to regular Statements, so presumably this example is acceptable without it.

Spec Ref (1st sentence): https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#details-7

**Comment by ty-** [comment]
Good point, I was focused on writing statements when I added this. The way the spec is worded, I had assumed it meant the LRS will add "Activity" when received. However, I suppose it could mean clients will also need to assume "Activity" if "objectType" is not specified when they receive a statement.

**Comment by garemoko** [comment]
There's a number of other optional properties not included in this statement. 

I think I'm slightly against this change for that reason, but don't feel strongly about it!

**Comment by ljwolford** [comment]
I don't have a strong opinion of this either, if it's already here, might as well accept it.

+1

**Comment by andyjohnson** [comment]
I'm in too, its an example of an optional property.

**Pull request merged**
