### PR TITLE
Rename 6.4 to "authorization", add 6.5 "security"

### LINKED ISSUE #726: Rename § 6.4
Apropos of @andyjohnson's [comment](https://github.com/adlnet/xAPI-Spec/pull/707#discussion_r33710520) in #707 (my follow-up [here](https://github.com/adlnet/xAPI-Spec/pull/707#discussion_r35506444)), and following indirectly from #725:

As it's been made explicitly clear on several occasions that infosec concerns are more or less orthogonal to the xAPI spec itself, I propose that § [6.4 Security](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#64-security) be renamed to "6.4 Authentication" or _maybe_ authorization (but that's a stretch), as it really only describes mechanisms of client authentication and really has little to do with security _qua_ security; at the very least, the title might mislead naïve readers to assume that the provisions in 6.4 provide security guarantees, which is at best laughable and at worst downright dangerous. 

In addition to disambiguating the intent and capabilities of the provisions in §6.4 by renaming it, I think it would be prudent to explicitly state in the same section that xAPI does _not_ directly address security, and implementors should follow industry best practices to achieve the level of security they require.

Again, I'd be happy to write the PR, posting issue for feedback.

### PR DESCRIPTION
**Pull request by canweriotnow**
Closes #726 

Decomplects "authentication" from the broader category of "security", and offers resources for (at least) transport-layer security based on White House CIO mandate, clarifies that internal security protocols for LRSs beyond authentication procedures are outside the scope of the current spec and the responsibility of the implementor.

### CODE REVIEW

**Comment by canweriotnow** [comment]
@andyjohnson I think the changes here are in line with the discussion in #726, let me know if anything needs to be added/altered, I'm happy to work on it some more if needed.

**Comment by garemoko** [comment]
@canweriotnow thanks for making this and sorry that the branches are confusing right now. 

Can you re-do or re-base this from the 1.0.3-Restructure branch and make the PR to there? 

https://github.com/adlnet/xAPI-Spec/compare/1.0.3-Restructure...yetanalytics:726_rename_security

**Comment by canweriotnow** [comment]
@garemoko no problem!

**Comment by canweriotnow** [comment]
Closing, will resubmit based on 1.0.3-Restrucuture

**Pull request closed without merging**
