### PR TITLE
List headers and tidy whitespace in contents

### LINKED ISSUE #565: Content-Length header requirement
From 7.10:

"The Content-Length header MAY be omitted, in order to avoid wasting LRS resources"

This is the first time this header is mentioned.  I suggest we either add more guidance in other places i.e. (in the APIs) or omit this requirement as it is only a MAY.

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #565. 

This involved bumping the numbers in the contents list, so I tidied up some whitespace there at the same time. 

This one likely needs discussion as we didn't reach consensus in the issue.

### CODE REVIEW

**Comment by andyjohnson** [comment]
+1

**Comment by garemoko** [comment]
This one has merge conflicts; will resolve once we have consensus that the change is good.

**Comment by garemoko** [comment]
Andrew to fix merge conflict

**Comment by garemoko** [comment]
Looks like I messed the merge conflict resolution up. Will re-create the PR from a clean branch.

**Comment by garemoko** [comment]
This can be closed once #676 is merged.

**Pull request closed without merging**
