### PR TITLE
1.0.3 Restructured!

### PR DESCRIPTION
**Pull request by andyjohnson**
This should complete the restructuring and splitting!  I've kept the original file (xAPI.md) until after this PR, but will delete it in a PR shortly after this one.

### CODE REVIEW

**Comment by garemoko** [comment]
I don't intend to review this PR in detail; I think we'll just have to check the final thing, but there's a couple of high level things: 

* I think we should keep the full TOC in all three documents

* markdown issue:
image

* The indentation looks wrong. Markdown issue?
image

* some odd spacing, is that intentional?
image

**Comment by rswetnam** [comment]
Does this pull request/merge replace self-closing anchor tags with two
sided ones?

On Tue, Jan 26, 2016 at 10:12 AM, Andrew Downes <notifications@github.com>
wrote:

> I don't intend to review this PR in detail; I think we'll just have to
> check the final thing, but there's a couple of high level things:
>
>    -
>
>    I think we should keep the full TOC in all three documents
>    -
>
>    markdown issue:
>    [image: image]
>    <https://cloud.githubusercontent.com/assets/1363163/12589884/f4f30104-c457-11e5-939f-9ae65f9acb96.png>
>    -
>
>    The indentation looks wrong. Markdown issue?
>    [image: image]
>    <https://cloud.githubusercontent.com/assets/1363163/12589906/1ea8db2c-c458-11e5-9eba-6eb67249a411.png>
>    -
>
>    some odd spacing, is that intentional?
>    [image: image]
>    <https://cloud.githubusercontent.com/assets/1363163/12589931/3e829f64-c458-11e5-836a-ec23d29143dc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/pull/864#issuecomment-175149709>.
>



-- 
Roger Swetnam
p.  604-408-5703
c.  778-848-3118

**Comment by andyjohnson** [comment]
Hey @rswetnam , not yet.  This was basically a cut and paste job.  I intend to go through each part with a semi-fine tooth comb and the anchor tags are something I'll be looking for.  @garemoko - I'll put the full TOC in each and see if that resolves the problem.  This change will also break links that go between document.  Will address per section.

**Comment by garemoko** [comment]
@andyjohnson Part 2 still looks wonky. There's some weird whitespace and a bunch of exra lines that might be the cause: 
image

**Comment by andyjohnson** [comment]
Going to merge this to proceed with splits and edits to each individual part.  Any corrections can be continued at the "Part" level.

**Pull request merged**
