### PR TITLE
Prefer "Total Learning Architecture"

### PR DESCRIPTION
**Pull request by oconnetf**
Fixes https://github.com/adlnet/xAPI-Spec/issues/988.

### CODE REVIEW

**Comment by andyjohnson** [comment]
Yep, thanks for this change.  +1.

**Comment by garemoko** [comment]
Why the change in line length?

**Comment by oconnetf** [comment]
Honestly, this came from our internal doc practice from GitHub. I think I did it reflexively more than consciously.

When editing docs, if each sentence is a full line, it's much easier to see changes within a given sentence.

I'm happy to unwind to something more closely resembling original line lengths.

**Comment by garemoko** [comment]
The spec has some specific-ish line lengths which are basically about the width of a normal sized window when viewing the markdown. In fact @andyjohnson recently went through and adjusted a large number of lines to make the lengths the same. 

I can definitely see the logic in your approach but 'that's not the way we do things round here' and consistency is more important.

**Comment by oconnetf** [comment]
Point taken. Edit made. Change committed.

**Comment by garemoko** [comment]
+1

**Comment by andyjohnson** [comment]
+1 and merging.  Thanks for the catch in the line breaks.

**Pull request merged**
