### PR TITLE
"Plain text body" error response fix

### LINKED ISSUE #538: Returning plain text in Concurrency
Within the Concurrency section there is the following requirement:

> * MUST return a plain text body explaining that the consumer SHOULD
>   * check the current state of the resource.
>   * set the "If-Match" header with the current ETag to resolve the conflict.

(ref: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#lrs-requirements-5)

Should this be interpreted as "text/plain" or non-binary? In other words is "text/html" considered "plain" or must it be "text/plain" and not anything else equating to non-encoded text?

### PR DESCRIPTION
**Pull request by fugu13**
Fixes #538

### CODE REVIEW

**Comment by garemoko** [comment]
Looks good! Are you also going to also address "and then add a general recommendation that, for error messages, servers would be advised to do content type negotiation + have plain text, html, and JSON responses, just as a matter of being good webizens." as part of this PR?

**Comment by garemoko** [comment]
Reply to myself - this is addressed in #613

**Comment by andyjohnson** [comment]
+1, @garemoko you in for +1 as well?

**Comment by garemoko** [comment]
Yep. "Looks good!" is en-GB for "+1"

**Pull request merged**
