### PR TITLE
Fix indentation error in performance appendix

### PR DESCRIPTION
**Pull request by alcesleo**

### CODE REVIEW

**Comment by vbhayden** [comment]
Thanks!

**Comment by alcesleo** [comment]
My pleasure!

**Comment by garemoko** [comment]
@vbhayden Shouldn't we be making changes to the dev branch instead of master?

**Comment by vbhayden** [comment]
Oh jfc I thought this was the xAPIWrapper repo.  It's been a long week, reverting and moving that over.

**Comment by vbhayden** [comment]
Reverted, sorry for confusion.

**Comment by vbhayden** [comment]
@alcesleo  can you resubmit the PR to target the dev branch?

**Comment by alcesleo** [comment]
Sure, no problem

**Pull request merged**
