### PR TITLE
Agent Profile API: Clarifications

### PR DESCRIPTION
**Pull request by garemoko**
Works towards #544 

Please don't merge this until #645 merges as I believe this will conflict and this will be easier to re-do. Still valuable to discuss the wording of this PR though.

### CODE REVIEW

**Comment by andyjohnson** [comment]
+1

**Comment by garemoko** [comment]
Did we miss discussing this on the call? It's a relatively minor change.

**Comment by andyjohnson** [comment]
This issue had only been open for 7 days so I wasn't going to include it in the big sweep.  There is currently a merge conflict now too.  Agreed it is minor.  It is +1 worthy imo if anyone else wants to take a quick peek!

**Comment by garemoko** [comment]
I'll resolve the merge conflict once this has 2 +1s to avoid having to do so twice!

**Comment by garemoko** [comment]
Appreciate this needs another +1. If we can get this merged today we could have a clean slate ready for another big batch.

**Comment by garemoko** [comment]
The diff is a bit messed up due to the conflict and some commits that have already been merged getting bundled in on this. You can see what actually changed here: https://github.com/garemoko/xAPI-Spec/commit/7ed8d315fb960293dab95b4fa6eaf788d31b9ba1

It's just moving that table up and adding the note.

**Pull request merged**
