### PR TITLE
Issues #695 #696 #633 (Section 4)

### LINKED ISSUE #695: case sensitivity of email addresses
The domain portion of emails is case insensitive. Could this case problems for the mbox_sha1sum property?

Also, the 'Statement Immutability and Exceptions' outlines a number exceptions to immutability. Email address domain case should be on that list. (Also the 'Statement Immutablity and Exceptions' section is missing an 'i' in 'Immutablity.')

Note: this only relates to the domain e.g. ```foo@doMaIn``` == ```foo@domain```

See http://stackoverflow.com/a/9808332/4214694

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #695 #696 #633

### CODE REVIEW

**Comment by andyjohnson** [comment]
+1

**Comment by vbudhram** [comment]
:+1:

**Comment by garemoko** [comment]
This has two +1s, but I'd be happier if one of @bscSCORM @brianjmiller @fugu13 had eyes on this particular one before merging.

**Comment by andyjohnson** [comment]
I'm good with that too @garemoko

**Pull request merged**
