### PR TITLE
Add requirements around IRI comparison

### PR DESCRIPTION
**Pull request by garemoko**
Addresses #69. 

Also tidies up overlapping requirements for Metadata Providers and Activity Providers and separates out requirements around IRIs themselves from requirements about the metadata hosted at the location of the IRI.

### CODE REVIEW

**Comment by andyjohnson** [comment]
+1

**Comment by garemoko** [comment]
This will probably conflict horribly with #910.

**Comment by bscSCORM** [comment]
Note to other reviewers, these requirements seem to be the only ones added:

##### LRS Requirements
 * When storing or comparing IRIs, LRSs SHOULD* handle them only by using one or more of the approaches 
 described in [5.3.1 (Simple String Comparison) and 5.3.2 (Syntax-Based Normalization) of RFC 3987](https://tools.ietf.org/html/rfc3987#section-5.3), and 
 SHOULD* NOT handle them using any approaches described in [5.3.3 (Scheme-Based Normalization) or 5.3.4 (Protocol-Based Normalization) of the same RFC](https://tools.ietf.org/html/rfc3987#section-5.3), 
 or any other approaches.

**Comment by bscSCORM** [comment]
:+1: and I think 5.3.2 should be pushed as a best practice. Systems not applying 5.3.2 are going to wind up with a lot of false negatives as browsers etc _do_ apply it, the scenarios in 5.3.3 and .4 seem less likely to come up.

**Comment by fugu13** [comment]
I broadly agree 5.3.2 is an improvement over not using them, but only broadly; i think the advantage is slight, and I think "a lot" will be "once in a blue moon, maybe less". I'd prefer to leave it as is for now, but would be amenable to talking about adding the 5.3.2 rec when we're doing the actual conversion to MUST.

Warning: this is mostly me meandering because I'm on a conference call where I'm mostly listening, at this point it's mostly an interesting question from an academic standpoint ;) . Anyone not interested in vagaries of normalization in practice can safely skip.

If the data's coming from a browser pre-normalized by URL (vs what? most people are clicking links generated by code, not pasting in, so it went in normalized 99.99% of the time), there's little need for the LRS to do anything, unless we're expecting the person doing things to go get the URL by looking at some link needing normalization, copying that, then being surprised when it doesn't work -- instead of just looking at the URL actually sent to the LRS.

It doesn't even come up for LRS-to-LRS considerations, really -- if one normalizes, it will do so on any IRIs it gets (oh, we should add a SHOULD* on that), and if one doesn't normalize and is being talked to by the one that does normalize, it'll only get one version.

What needs to happen for the 5.3.2 normalizations to matter is for a URL to be sent to the LRS in one form *and* another form, and since most URLs sent to an LRS are entered by a human or read off a browser (and only one of those), the likelihood that they'll differ along normalization is pretty small.

**Comment by fugu13** [comment]
One thing that my meandering did turn up is, we should add the following:

LRSs SHOULD* apply the same IRI comparison and normalization rules with all IRIs in parameters and fields defined to contain IRIs.

(The defined to contain IRIs language is there to make clear this isn't a call to parse text fields looking for IRIs).

**Comment by andyjohnson** [comment]
+1 for @fugu13's suggestion

**Comment by garemoko** [comment]
Added that as suggested by @fugu13

**Comment by andyjohnson** [comment]
+1 for PR

**Comment by garemoko** [comment]
^^ Called it: https://github.com/adlnet/xAPI-Spec/pull/902#issuecomment-205735873

**Comment by bscSCORM** [comment]
👍

**Comment by garemoko** [comment]
Still working on the conflict, but just a note that the Metadata Provider section was very conflicted, so once I commit the fix @andyjohnson please check carefully that I didn't lose any of your changes.

**Comment by garemoko** [comment]
@andyjohnson please don't merge this; I messed up the conflict fix.

**Comment by andyjohnson** [comment]
No problem.  Let me know when it is ready and I'll be careful about
checking it for anything that was in my PR.

On Thu, Apr 21, 2016 at 2:40 PM, Andrew Downes <notifications@github.com>
wrote:

> @andyjohnson <https://github.com/andyjohnson> please don't merge this; I
> messed up the conflict fix.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/pull/902#issuecomment-213058296>
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
Made a new PR; closing this.

**Pull request closed without merging**
