### PR TITLE
Nicer description of actor

### LINKED ISSUE #754: Agent
Section 2.3.2 says than an actor is:
> A mandatory Agent or Group Object.

What is a mandatory Agent?  Are there other types of Agents?  The document contains no definition of an Agent.

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #754

### CODE REVIEW

**Comment by garemoko** [comment]
Note that we say that Actor is required here: https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#24-statement-properties

**Comment by fugu13** [comment]
I think actor should be lowercased (and I think we're doing a particular style for the text of property names?). It isn't a type of entity, unlike Agent and Group, it is a property on a Statement.

**Comment by garemoko** [comment]
It should be capitalized. [style guide](https://github.com/adlnet/xAPI-Spec/blob/master/CONTRIBUTING.md#style-guide)

**Comment by andyjohnson** [comment]
+1 and agreed to revise on call, merging

**Pull request merged**
