### PR TITLE
What happens if a batch contains conflicting statement ids.

### LINKED ISSUE #839: LRS SHOULD reject batches of statements with internal statement id conflict.
```If the LRS receives a Statement with an id it already has a Statement for, it SHOULD verify the received Statement matches the existing one and SHOULD return 409 Conflict if they do not match.```

I propose changing to:

```If the LRS receives a Statement with an id it already has a Statement for, or receives a batch containing multiple statements with the same id, it SHOULD verify the Statements match and SHOULD return 409 Conflict if not.```

As this is already a SHOULD, I think this is ok for 1.0.3.

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #839

### CODE REVIEW

**Comment by garemoko** [comment]
I'm going to bundle #740 into this too

**Comment by andyjohnson** [comment]
"if they do not" instead of "if not", great catch on this scenario!

**Comment by garemoko** [comment]
Fixed. I hit this when I accidentally sent a batch of statements with duplicated ids following a copy-paste error.

**Comment by andyjohnson** [comment]
+1!

**Comment by fugu13** [comment]
I think if we allow this rejection the error code should likely be 400. 409 in the HTTP spec is clear that it only applies if the submitted data conflicts with the current (pre-request) state of the resource.

**Comment by fugu13** [comment]
Also, we should consider making this requirement a SHOULDstar; duplicates in one batch are pretty bad behavior.

**Comment by bscSCORM** [comment]
^^ I agree with @fugu13's comments above

**Comment by garemoko** [comment]
@fugu13 @bscSCORM thanks for the comments; I shouldn't have just assumed it could be bundled in with the other requirement. 

Given those comments, I think [Ben's branch] is actually closer to the solution we want than this one, so it may be best to close this and reopen #851.

**Pull request closed without merging**
