### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by aakoch**
1. If an anchor tag was immediately above a line with a header, it wasn't rendered correctly, so I added lines.
2. There were some anchors that weren't closed, causing some issues.
3. Fix typos (misspellings)
4. Fix link on page
5. Add space between hash and character for proper formatting

### CODE REVIEW

**Comment by garemoko** [comment]
I believe items 1 and 2 are fixed by #1034. 

The other typos and link fixes should be PRed to the dev branch instead of master. 

Item 5 isn't covered by #1034 and *does* need to be addressed in master. It also needs to be addressed for the [part one header](https://github.com/garemoko/xAPI-Spec/blob/fix-markdown(1033)/xAPI-About.md#partone) and 'How to Contribute' in CONTRIBUTING.md (which you addressed in #1036)

**Comment by andyjohnson** [comment]
@garemoko 's PR was larger so I went with that one first.  There are now conflicts.  After this round of merges, I'll update dev (since there haven't been any PRs to it) with the markdown fix so we don't have to go through that again.  Thanks so much for helping on this, but if you could work from the new merge, I and we would appreciate it a ton!

**Comment by garemoko** [comment]
I believe the only bit of this PR we need to keep is this typo: https://github.com/adlnet/xAPI-Spec/pull/1035/files#diff-e357caff41f2a13c998b2f789a7820b5R1931

The other issues have either already been addressed or are covered in https://github.com/adlnet/xAPI-Spec/pull/1039

**Comment by garemoko** [comment]
The changes in this have now been merged into dev, so this can be closed.

**Comment by creighton** [comment]
We believe all of the changes have been addressed. If there are any issues, please feel free to reopen.

**Pull request closed without merging**
