### PR TITLE
1.0.3 restructure

### PR DESCRIPTION
**Pull request by rswetnam**
Move Revision History to Appendix

### CODE REVIEW

**Comment by garemoko** [comment]
I'm going to assume that the move didn't lose anything. It *looks* fine and my normal text comparison doesn't seem to be working. @rswetnam for any future PRs, if you are moving text, please do the move as a separate PR from any edits. This allows us to more easily distinguish actual changes from moved content. 

Some feedback:

* I don't agree with moving the ADL Director's message and list of contributors. 
* Edits to the table of contents don't really matter at the moment since the whole lot needs re-doing so I didn't review that bit. 
* The anchors look helpful
* I'm happy with either the existing or new title for that first section.

**Comment by andyjohnson** [comment]
@rswetnam can you please open this as an issue instead?  We did have a feedback period for moving this text and wanted it outside the actual "Parts" to look more like how W3C sets up their specs/pages.  I'm fine with revisiting that strategy, but we are almost out of the woods on this restructure PR.  My first priority will be getting the TOC and links right and will have that done by next Wednesday if we can get the last PR in (have merging conflicts :( and perhaps a bit more agreement on diagrams/text).  Once we have a more viewable document (and soon to be set of documents), Let's re-evaluate.

**Comment by rswetnam** [comment]
Sure, I'm fine with that - are you able to say no to the pull request or do
I need to do something? - I'm fine with just dropping it until after the
restructure has been done.



On Fri, Sep 4, 2015 at 10:00 AM, Andy Johnson <notifications@github.com>
wrote:

> @rswetnam <https://github.com/rswetnam> can you please open this as an
> issue instead? We did have a feedback period for moving this text and
> wanted it outside the actual "Parts" to look more like how W3C sets up
> their specs/pages. I'm fine with revisiting that strategy, but we are
> almost out of the woods on this restructure PR. My first priority will be
> getting the TOC and links right and will have that done by next Wednesday
> if we can get the last PR in (have merging conflicts :( and perhaps a bit
> more agreement on diagrams/text). Once we have a more viewable document
> (and soon to be set of documents), Let's re-evaluate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/pull/748#issuecomment-137792132>.
>



-- 
Roger Swetnam
p.  604-408-5703
c.  778-848-3118

**Comment by andyjohnson** [comment]
You can go ahead and close this.  Be aware that your changes are still live in your branch, so you may want to make a new branch off the merged 1.0.3 restructure.

Thanks, @rswetnam !

**Pull request closed without merging**
