### PR TITLE
Many tweaks in Part 2

### PR DESCRIPTION
**Pull request by garemoko**
See #798

The Requirements for Activity Providers which i removed are covered in the Metadata section.

### CODE REVIEW

**Comment by andyjohnson** [comment]
Agree that "Activities" in the context of Immutability should be Activity Definition

Agree with removing unenforceable requirements on Activity Providers about Verbs

One small typo:  when a conflict with another system occurs, it’s not possible to determine which activity is intended  (capitalize activity)

+1 with that fix

**Comment by garemoko** [comment]
@andyjohnson I didn't remove those Verb requirements due to enforceability, but rather because they are replicated in the metadata section.

**Comment by andyjohnson** [comment]
Ahh my mistake, I must have looked at a different version.  Still +1 !

**Comment by ljwolford** [comment]
+1

**Pull request merged**
