### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #683: Contributing Doc Updates
Minimally the README.md in the root of the repo should be updated to tell users to PR against the "current development branch" and we might even include what branch that is since it doesn't have the same version restrictions as the specification itself.

Alternatively we could move most of what is in the README into a CONTRIBUTING.md file so that GitHub automatically displays a message of how to do so. See https://github.com/blog/1184-contributing-guidelines. The instructions should also be reviewed for continued accuracy, and we might even include a "simple start" section that describes how to PR using GitHub directly since they have online editing capability now.

### PR DESCRIPTION
**Pull request by garemoko**
Fixes #683

Probably the best way to review this is to look at https://github.com/garemoko/xAPI-Spec/tree/contributing/

Note that this PR is deliberately being made against Master. We'll need to ensure that any future changes to README.md and CONTRIBUTING.md are made against master.

### CODE REVIEW

**Comment by garemoko** [comment]
Just realised that this is already going to conflict as we already made changes to README.md. 

I'll move those across.

**Comment by brianjmiller** [comment]
Thanks for taking the first stab at this!

I think the README could be beefed up a little and while accurate I think the wording of "Do not implement this version." needs more information around it. It'd be nice to have some copy explaining that they can implement the spec, and that they should review the changes made in the development version for inclusion in the near future.

On the contributing piece it might make sense to include information on the MUST vs. SHOULD* (unless that is already in the spec). I'd also like to see a section, probably the first, about how to submit a PR using just Github's site since they should now be able to do that. We need not scare off people who don't want to install git, deal with forking, etc. just to edit typos and/or prose.

**Comment by garemoko** [comment]
Good point. We could also link to GitHub for Mac and GitHub for Windows. For spec work I never use terminal except in case of conflicts and we shouldn't expect new contributors to handle their own conflicts.

**Comment by garemoko** [comment]
Looks like we already link to github clients. 

How's this now?

**Comment by andyjohnson** [comment]
Looks good, and since something is better than nothing, I'm merging (seriously, great job on this, though :)! )

**Pull request merged**
