### PR TITLE
eTag header for PUT/POST

### PR DESCRIPTION
**Pull request by garemoko**
Fixes https://github.com/adlnet/xAPI-Spec/issues/439

### CODE REVIEW

**Comment by andyjohnson** [comment]
+1

**Comment by fugu13** [comment]
I'd tweak that slightly, to "SHOULD* add the ETag HTTP header for the entity just created or modified to the response".

Re: concern from the issue thread, making it a SHOULD* doesn't impact clients at all -- clients that don't want to react the header don't need to check for it, and can keep acting as they have been. Clients that are updated to notice the ETag header will also be able to act reasonably if it isn't there.

**Comment by garemoko** [comment]
Good suggestion @fugu13. That's done now.

**Comment by andyjohnson** [comment]
So with @fugu13 's tweak making it in, I'm going to consider that a +1 and merge this

**Pull request merged**
