### PR TITLE
remove all reference to reporting systems/tools

### LINKED ISSUE #638: Define "reporting system"
In a few places we introduce the concept of a reporting system. E.g. ```A reporting system SHOULD NOT show voided or voiding Statements by default ```. This could be confusing as most LRS products likely are also reporting systems to some degree. When we mention reporting systems what we mean is "Some system that might be the LRS that's displaying data to the user rather than returning data via the API". We're talking about a different role, which may or may not be the same actual product. 

We should look to clarify our use of the term "reporting system" and standardise similar but different terms if/where we use them. I suggest something similar to what I'm proposing for the metadata provider/consumer roles in this commit: https://github.com/garemoko/xAPI-Spec/commit/12ba2e15789fae63158e04ac245e02663b81c968

### PR DESCRIPTION
**Pull request by garemoko**
* Fixes #638 via a different approach than #662 

* Explicitly states that non-LRS systems can implement one or more LRS endpoints/methods and gives an example. Clarifies that systems which do so are not LRSs. I added this in this PR because I was starting to go down this route in the definition of reporting systems and felt it didn't belong in a definition.

### CODE REVIEW

**Comment by brianjmiller** [comment]
:+1:. The only question I had is whether "querried" is correct by British English or a typo, a cursory search suggests typo.

**Comment by andyjohnson** [comment]
Client should be capitalized where added, otherwise merge conflict and then +1!

**Comment by garemoko** [comment]
Working on this conflict now

**Comment by garemoko** [comment]
Conflict and comments resolved (13 days ago apparently Github??) 

Should be good to merge.

**Comment by garemoko** [comment]
@andyjohnson I think this has two +1 (assuming you're happy with the capitalisation) - can we merge?

**Pull request merged**
