### PR TITLE
Prefer "HTTP" to "this scheme".

### PR DESCRIPTION
**Pull request by oconnetf**
This edit is intended to resolve https://github.com/adlnet/xAPI-Spec/issues/908.

### CODE REVIEW

**Comment by garemoko** [comment]
+1

@andyjohnson I suggest merging this before your edits to part 3 I know you were going look at this section closely.

**Comment by andyjohnson** [comment]
I'm already in the middle, so I'll probably end up closing this as it will be easier for me to grab the same change than to resolve the conflict.  Thanks, though @oconnetf !  I'll leave this open until it is indeed done.

**Comment by oconnetf** [comment]
Honestly, I just wanted an opportunity to submit a Pull Request. :)

**Comment by andyjohnson** [comment]
I actually ended up re-writing this part in the latest PR, we can discuss there!

**Pull request closed without merging**
