### PR TITLE
Appendices tidy up

### PR DESCRIPTION
**Pull request by garemoko**
This PR is now ready for review. 

I have: 
* Update links to appendices within the document
* Move the list of contributors to contributing.md 
* Edited the TOC to reflect the changes
* Moved all appendices and changed their anchors
* Changed the Revision History title (added "Appendix A: ")
* Changed Appendix letters.

### CODE REVIEW

**Comment by andyjohnson** [comment]
Very well done.  I noticed one small thing:

I'd replace:

You can and should look at the development version of the specification for reference, but be aware that this version has not been published, could contain errors and might be changed before it is released.

with (could changed to ;it could)

You can and should look at the development version of the specification for reference, but be aware that this version has not been published; it could contain errors and might be changed before it is released.

**Comment by garemoko** [comment]
That whole file (readme.md) was copied from master with no changes, but I've made the change for you anyway.

**Comment by garemoko** [comment]
Fixes #741

**Comment by garemoko** [comment]
There were several conflicts here. I'm pretty sure I handled them all correctly. It'd be good to get this merged before we have many more PRs.

**Pull request merged**
